import { PGlite } from '@electric-sql/pglite';
import { pgcrypto } from '@electric-sql/pglite/contrib/pgcrypto';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const db=new PGlite({extensions:{pgcrypto}});
try {
 await db.exec(fs.readFileSync(new URL('./fixtures/autoridad_bootstrap.sql',import.meta.url),'utf8'));
 for(const name of ['20261001234206_operaciones_pedidos_atomicas.sql','20261001234848_cortes_folios_reportes_atomicos.sql','20261001235227_venta_intencion_resumen_periodo.sql','20261002175251_auditoria_integridad_operativa.sql','20261002175257_autoridad_login_entrada_publica.sql']) await db.exec('BEGIN;'+fs.readFileSync(new URL('../supabase/migrations/'+name,import.meta.url),'utf8')+'COMMIT;');
 const A='00000000-0000-4000-8000-000000000001', B='00000000-0000-4000-8000-000000000002', OWNER='00000000-0000-4000-8000-000000000010', TERM='00000000-0000-4000-8000-000000000011', ADMIN='00000000-0000-4000-8000-000000000012';
 await db.query("insert into sucursales(id,nombre,folio_prefijo) values($1,'A','A'),($2,'B','B')",[A,B]);
 await db.query("insert into auth.users(id,email) values($1,'owner@fixture.local'),($2,'terminal-'||$4||'@pos.confetti.local'),($3,'admin@fixture.local')",[OWNER,TERM,ADMIN,A]);
 await db.query("insert into usuarios_pos(id,auth_user_id,nombre,rol,activo,sucursal_id,pin_hash) values($1,$1,'Owner','dueño',true,$4,extensions.crypt('1234',extensions.gen_salt('bf'))),($2,$2,'Technical','caja',false,$4,null),($3,$3,'Manager','administrador',true,$5,extensions.crypt('5678',extensions.gen_salt('bf')))",[OWNER,TERM,ADMIN,A,B]);
 await db.query('insert into app_private.terminales_pos(auth_user_id,sucursal_id) values($1,$2)',[TERM,A]);
 const identity=async(id)=>db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);
 await identity(TERM); await db.exec('SET ROLE authenticated');
 assert.equal((await db.query('select pos_sucursal() as s,pos_is_admin() as admin')).rows[0].s,A);
 assert.equal((await db.query('select pos_is_admin() as admin')).rows[0].admin,false);
 await assert.rejects(()=>db.query('select pin_hash from usuarios_pos'),/permission denied/);
 await assert.rejects(()=>db.query("update usuarios_pos set rol='dueño' where id=$1",[TERM]),/permission denied/);
 await assert.rejects(()=>db.query('select actualizar_usuario_pos($1,$2::jsonb)',[OWNER,JSON.stringify({activo:false})]),/SOLO_DUENO/);
 await assert.rejects(()=>db.query("select login_pos('1234',null)"),/permission denied/);
 await assert.rejects(()=>db.query("select autenticar_pin_pos('1234',null,'fake')"),/permission denied/);
 await db.exec('RESET ROLE'); await identity(ADMIN); await db.exec('SET ROLE authenticated');
 assert.equal((await db.query('select pos_sucursal() as s,pos_is_admin() as admin')).rows[0].s,B);
 assert.equal((await db.query('select pos_is_admin() as admin')).rows[0].admin,false);
 await db.exec('RESET ROLE'); await identity(OWNER); await db.exec('SET ROLE authenticated');
 await assert.rejects(()=>db.query('select actualizar_usuario_pos($1,$2::jsonb)',[OWNER,JSON.stringify({activo:false})]),/ULTIMO_DUENO/);
 await db.query('select actualizar_usuario_pos($1,$2::jsonb)',[ADMIN,JSON.stringify({activo:false})]);
 await db.exec('RESET ROLE'); await identity(ADMIN); await db.exec('SET ROLE authenticated');
 assert.equal((await db.query('select pos_sucursal() as s,pos_is_admin() as admin')).rows[0].s,null);
 await db.exec('RESET ROLE'); await identity('');
 for(let i=0;i<5;i++) await db.query("select autenticar_pin_pos('0000',null,'fixture-ip')");
 let result=(await db.query("select autenticar_pin_pos('1234',null,'different-ip') as r")).rows[0].r;
 assert.equal(result.ok,false);assert(result.espera_segundos>0);
 await db.exec("update app_private.login_pin_estado set bloqueado_hasta=now()-interval '1 second'");
 result=(await db.query("select autenticar_pin_pos('1234',null,'fixture-ip') as r")).rows[0].r;
 assert.equal(result.ok,true);
 assert.equal((await db.query("select count(*) as n from app_private.login_pin_estado where clave='principal:selector'")).rows[0].n,0);
 await db.exec('SET ROLE anon');
 await assert.rejects(()=>db.query("insert into pedidos(sucursal_id,origen,estado,cliente_nombre,cliente_telefono,kilos,total_final) values($1,'web','pendiente','Fixture','0000000000',1,1)",[A]),/permission denied/);
 const payload={sucursal_id:A,cliente_nombre:'Fixture',cliente_telefono:'0000000000',kilos:1,total_final:100,fecha_entrega:'2099-10-01'};
 const folio=(await db.query('select crear_pedido_web($1::jsonb) as f',[JSON.stringify(payload)])).rows[0].f;assert(folio);
 await assert.rejects(()=>db.query('select crear_pedido_web($1::jsonb)',[JSON.stringify({...payload,total_abonado:100})]),/PAGO_WEB_PROHIBIDO/);
 await assert.rejects(()=>db.query('select crear_pedido_web($1::jsonb)',[JSON.stringify({...payload,credito_historico:100})]),/CAMPO_PEDIDO_PROTEGIDO/);
 await assert.rejects(()=>db.query('select crear_pedido_web($1::jsonb)',[JSON.stringify({...payload,total_final:-1})]),/IMPORTE_WEB_INVALIDO/);
 await assert.rejects(()=>db.query('select crear_pedido_web($1::jsonb)',[JSON.stringify({...payload,estado:'pagado'})]),/estado invalido/);
 console.log('PASS: terminal inactive scoped; manager branch scoped; no hash/escalation; last owner; inactive session; cooldown shared/reset; anon insert denied; public RPC valid/invalid');
} catch(e) { console.error(e.message,e.where,e.detail);process.exitCode=1; } finally { await db.close(); }
