import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import ts from 'typescript';
const source=fs.readFileSync(new URL('../supabase/functions/transcribir-nota-voz/index.ts',import.meta.url),'utf8').replace(/^import .*;$/gm,'');
let handler,mode='anon',fetches=0,completions=[];
const env={SUPABASE_URL:'https://fixture.supabase.co',SUPABASE_ANON_KEY:'fixture-public',SUPABASE_SERVICE_ROLE_KEY:'fixture-service',OPENAI_API_KEY:'fixture-ai'};
const client=key=>key==='fixture-service'?{rpc:async(name,args)=>{completions.push(args);return {data:true};}}:{auth:{getUser:async()=>{if(mode==='identity-network')throw Error('offline');return mode==='anon'?{error:{message:'no user'}}:{data:{user:{id:'fixture-actor'}}};}},rpc:async()=>{if(mode==='rpc-network')throw Error('offline');if(mode==='denied')return {error:{message:'denied'}};if(mode==='cache')return {data:{estado:'completa',transcript:'cached'}};if(mode==='pending')return {data:{estado:'pendiente'}};return {data:{estado:'nueva',clave:'fixture',lease:'00000000-0000-4000-8000-000000000001'}};}};
const fetch=async url=>{fetches++;if(mode==='download-failure')throw Error('offline');if(url.includes('api.openai.com'))return new Response(JSON.stringify({text:'Hola fixture'}),{headers:{'content-type':'application/json'}});assert.equal(url,'https://fixture.supabase.co/storage/v1/object/public/notas-voz/fixture.webm');return new Response(new Uint8Array([1,2,3]),{headers:{'content-type':'audio/webm'}});};
const ctx=vm.createContext({URL,Response,Request,Headers,Blob,FormData,Uint8Array,AbortController,setTimeout,clearTimeout,console:{warn:()=>{}},Deno:{env:{get:k=>env[k]}},createClient:(_,key)=>client(key),serve:h=>{handler=h;},fetch});
vm.runInContext(ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText,ctx);
const call=async(audioUrl='https://fixture.supabase.co/storage/v1/object/public/notas-voz/fixture.webm')=>{const response=await handler(new Request('https://fixture.local',{method:'POST',headers:{authorization:'Bearer fixture',origin:'https://pasteleria-confetti.vercel.app','content-type':'application/json'},body:JSON.stringify({audioUrl})}));assert.equal(response.status,200);return response.json();};
for(const m of ['anon','identity-network','denied','rpc-network','pending']){mode=m;const before=fetches;assert.equal((await call()).ok,false);assert.equal(fetches,before);}
mode='cache';assert.equal((await call()).transcript,'cached');assert.equal(fetches,0);
mode='valid';for(const url of ['https://evil.local/fixture.webm','https://fixture.supabase.co/storage/v1/object/public/notas-voz/%FF.webm','https://fixture.supabase.co/storage/v1/object/public/notas-voz/a/b.webm']){assert.equal((await call(url)).ok,false);assert.equal(fetches,0);}
assert.equal((await call()).transcript,'Hola fixture');assert.equal(fetches,2);assert.equal(completions.at(-1).p_ok,true);
mode='download-failure';assert.equal((await call()).ok,false);assert.equal(completions.at(-1).p_ok,false);
console.log('PASS: real Edge handler rejects public JWT/foreign object before I/O; cached/pending requests do not call AI; strict URL; server-only cache completion; identity/network/provider failure preserves optional-audio fallback');
